### ISSUE TITLE
Review Curve a3crv strat

### ISSUE THREAD

**Issue by hsukev** [yearn/yearn-strategies#19]
**Description:** 
Strategy stakes Curve aave pool tokens (`a3crv`) into the curve gauge and optimally resells `CRV` gains  to reserves in the Curve aave pool (`dai, usdc, usdt`)

The sell logic checks `uniswap` `crv -> dai/usdc/usdt` , then checks `curve pool` `dai/usdc/usdt -> a3crv` and selects the path that would maximize `a3crv`

**Repo:** 
[StrategyCurveA3crv](https://github.com/hsukev/yearn-strats)

**Tags:**

**Notes:**
 Has not been deployed yet

**Comment by TheRyanMiller** [comment]
Test

**Comment by TheRyanMiller** [comment]
## Strategy
- This is easy to follow and clean. Clearly based on some existing Curve strats.
- By same token, I'd urge you to be the first one to properly implement `estimatedTotalAssets` ([see comments here](https://github.com/iearn-finance/yearn-vaults/blob/5591453b6f3627bd50f304616ece243128488892/contracts/BaseStrategy.sol#L395))so that it accounts for the `want`-denominated value of your strategy's holdings. Future v2 Curve strats will be able to recycle your logic for this & everyone wins 🙂.
- Logic for determining the best stablecoin to buy with CRV is flawed in that it doesn't take into account the expected output of the swap. At time of writing this, 10,000 CRV can buy 200 more USDC than it can DAI. Not sure how much impact this would have in effect.
## Tests 
- I was getting errors out the gates with tests. Could be something to do with my env? I was able to resolve with `.from_explorer` on [this line](https://github.com/hsukev/yearn-strats/blob/110c865fb849a38999cf0614b84c9c1090add94f/tests/conftest.py#L26)
- APY figures were showing obscenely high. To fix this, remove all the fixtures that make new deposits into you vault (e.g. pleb, chad, greyhat). You're not using them for anything else. Also reduce the the initial deposit by `whale` to something like 1e20.

**Comment by hsukev** [comment]
@TheRyanMiller Thanks for the feedback! Is it necessary to account for the farmed token? The strategy harvests and sells CRV in the same method so it'll should always sell all rewards and never actually hold CRV. If there's some way for the farmed tokens to be held, I'm not really sure how to estimate that amount in terms of `want` . Any suggestions?

**Comment by matkam** [comment]
There is a `claimable_reward(...)` function in the curve gauge contracts, that will return the amount of CRV you can claim without claiming them. But I'm not sure you can call it from `estimatedTotalAssets(...)`, so it may not be possible to include CRV rewards in the estimate. That said, I'd be happy to recycle your logic if you figure it out 😃.

**Comment by TheRyanMiller** [comment]
> But I'm not sure you can call it from `estimatedTotalAssets(...)`, so it may not be possible to include CRV rewards in the estimate. That said, I'd be happy to recycle your logic if you figure it out 😃.

@matkam - I think it should be possible, unless I'm missing something. Kevin would be able to add that gauge fxn as an interface, and then query `claimable_reward` by passing in the voter address `0xf147b8125d2ef93fb6965db97d6746952a133934` as the argument.

@hsukev - Doing this would ofc break some some code where you fall back on `estimatedTotalAssets()` to represent your amount staked, [like here](https://github.com/hsukev/yearn-strats/blob/110c865fb849a38999cf0614b84c9c1090add94f/contracts/StrategyCurveA3CRV.sol#L125). Would need to do something like [this](https://github.com/matkam/yearn-strategies/blob/45c3209bf9aeff4e4173cc915c8d1bcf3b87d678/contracts/StrategyCurveEcrv.sol#L99) to handle.

@hsukev - As far as finding the value of farmed token, you can simply use the an estimate price via a DEX. You'll need to call just [this simple view-only function here]((https://uniswap.org/docs/v2/smart-contracts/library/#getamountout) on your DEX for your CRV to stable wap, and then to convert to `want` you can use [get_virtual_price](https://github.com/curvefi/curve-contract/blob/c7e17267947d0cbb6543897aaf03b227d36d801c/contracts/pools/aave/StableSwapAave.vy#L326) on the Curve Pool contract. Best practice would be to underestimate by a few % for safety.

**Comment by hsukev** [comment]
Addressed most of the issues above. We couldn't figure out how to get `claimable_rewards()` or `claimable_tokens()` to work so it's been commented out. @Macarse I think it's ready for review now

**Comment by hsukev** [comment]
closing this as we're not pushing out anymore curve strats 😢
