### ISSUE TITLE
Review 1inch strategy

### ISSUE THREAD

**Issue by fameal** [yearn/yearn-strategies#40]
**Description**: 1inch strategy

**Commit (hash)**: 

**Tag**:

**Repo**: https://github.com/akshaynexus/1inchgov-stake

Repo: 
**Scope**: (List link to files)
- https://github.com/akshaynexus/1inchgov-stake/blob/master/contracts/Strategy.sol

**Additional References or Repo** (Link to underlying protocols or relevant documents):

Governance: https://etherscan.io/address/0x0F85A912448279111694F4Ba4F85dC641c54b594
Stake: https://etherscan.io/address/0xA0446D8804611944F1B527eCD37d7dcbE442caba#code

**Deployed Contract** (etherscan link): 
Strategy : https://etherscan.io/address/0xb12f6a5776edd2e923fd1ce93041b2000a22ddc7
Vault : https://etherscan.io/address/0xb8c3b7a2a618c552c23b1e4701109a9e756bab67

**Review Ongoing By**:
- [x] Doug
- [x] Poolpi

**Review Completed By**:
- [x] Doug
- [x] Poolpi

**Comment by poolpitako** [comment]
I already reviewed. LGTP

**Comment by dougstorm** [comment]
Reviewed the code, and staking and rewards contract, only thing i found as a very unlikely edge case is that governance mothership can change/add modules and potentially introduce a bug that reverts on stake and unstake for some reason if code is faulty. 

In that unlikely scenario the strategy would have its funds stuck as well as all users, so expectation is that the underlying protocol is trusted to fix that if it happens, since the strategy cannot do much to exit during emergency situation.
